### ISSUE TITLE
Old AccelStepperI2C has same includes as new I2Cwrapper: confusing conflict

### ISSUE THREAD

**Issue by awgrover** [ftjuh/I2Cwrapper#2]
If you have the old `AccelStepperI2C` installed with this new library, it won't pick up the right `.h` file (I think it does alphabetical order!).

How much of a problem is that? I think that everyone who upgrades to this new library will feel the pain. There does not seem to be a good deprecation/conflict mechanism.

There were some questions about deprecation/conflict:
* [https://github.com/arduino/arduino-cli/issues/1001]() "use deprecation/warnings in the old .h"
* [https://forum.arduino.cc/t/issue-warning-for-deprecated-library-function/691200/2]() how to deprecate

`#include <PinI2C.h>`
Causes
```
Multiple libraries were found for "PinI2C.h"
 Used: /home/awgrover/Arduino/libraries/AccelStepperI2C
 Not used: /home/awgrover/Arduino/libraries/I2Cwrapper
exit status 1
```
But, that is the last message. And, for other `.h` can cause a bunch of preceding errors that are confusing, like

    someclass does not name a type

**Comment by ftjuh** [comment]
Do you actually need to use both libraries side by side or is this a theoretical problem?

I'm asking as I don't expect there are a lot of users who will actually feel that pain. AccelStepperI2C is already marked as obsolete, it's further use is discouraged (which I will make more clear after the initial release) and it is recommended to remove it when upgrading to I2Cwrapper. Also, existing controller sketches will compile without changes after upgrading. So I don't see the need for supporting parallel installation.

That's not to say that if there is a simple solution, I'll be happy to implement it, e.g. like suggested [here](https://github.com/arduino/arduino-cli/issues/1001#issuecomment-702496069). Otherwise, let's wait if people will actually report this as a problem.

On a sidenote, the links in your comment do not link the the URL in the links' text, but back to this issue, so that I have to copy & paste them manually.

**Comment by ftjuh** [comment]
AccelStepperI2C is now deprecated and is scheduled to be pulled from the library manager.
